### ISSUE TITLE
removing artist name from the song title when playing from youtube

### ISSUE THREAD

**Issue by alexou2** [Moon-0xff/gnome-mpris-label#52] opened 2023-05-06 21:03 UTC
gh told me to create an issue in order to fork the project.
How do I test if the feature I want to add works or not?

**Comment by Batwam** [comment] 2023-05-07 01:50
We have an open for for advanced field filtering using regex here: https://github.com/Moon-0xff/gnome-mpris-label/pull/31
this would probably achieve what you are looking for: https://github.com/Batwam/gnome-mpris-label-batwam/tree/filtering_new
![image](https://user-images.githubusercontent.com/56710655/236653541-e1e845d1-ce7c-49b3-908a-959a9729ac87.png)

As a lot of youtube videos include the artist name and the browser will feed the video title to `title`, you might be getting the artist twice. Is this what you mean? With the current stable version, if you change the fields from Artist/none/title:
![image](https://user-images.githubusercontent.com/56710655/236653449-79f544f0-86b3-44dd-a26d-2c6e344b0d92.png)
to title/none/none, it will remove the duplicated artist at least:
![image](https://user-images.githubusercontent.com/56710655/236653461-7bb80a08-8d27-4b74-8891-73b4a5032f92.png)

**Comment by alexou2** [comment] 2023-05-07 02:19
Ohh...
Is there something else that i can do to contribute to the project?

**Comment by Batwam** [comment] 2023-05-07 02:23
You can certainly test that branch and see if it does what you need. It was initially intended the extend the ability to filter some types of text like "featuring" "live at ..." which make the titles too long in a way people can customise. I am not 100% of if it does what you are looking for?

We'd be interested to hear about users about whether it works or not, what part they find useful/confusing, etc...

**Comment by alexou2** [comment] 2023-05-07 02:36
I was just looking for a way to help in the project in some way, since i like how it works

**Comment by alexou2** [comment] 2023-05-07 02:38
I also don't have this option 
![image](https://user-images.githubusercontent.com/92472779/236654751-fd4809b7-10f6-490d-8d43-53f658af692d.png)

**Comment by alexou2** [comment] 2023-05-07 04:28
how do I get the menu where I can filter the name? I tries cloning the fork you mentioned, but I got the same interface as before

**Comment by Batwam** [comment] 2023-05-07 04:31
Did you log out and log back in to reload the extension? In X11, you can also type alt+F2 and r to restart gnome-shell.

**Comment by alexou2** [comment] 2023-05-07 04:33
I logged out and back in and it didn't work. I cloned the fork and then ran the install script.

**Comment by Batwam** [comment] 2023-05-07 04:41
The extension manager will overwrite the files in the background if it finds that they have a lower version number than what is available on extensions.gnome.org. It shouldn't happen though as they should both be version 14. 

Anyway, I updated metadata.json to version 15 in the fork. Could you try again?

**Comment by alexou2** [comment] 2023-05-07 04:49
I cloned the fork but the version didn't update and I still have the issue

**Comment by Batwam** [comment] 2023-05-07 04:57
That's because you are in the main branch by default. Do a `git checkout filtering_new`

**Comment by alexou2** [comment] 2023-05-07 05:04
thx now it works.

**Comment by Batwam** [comment] 2023-05-07 05:16
Does this do what you want? Please report any feedback in #31

**Comment by alexou2** [comment] 2023-05-07 05:17
yes

**Comment by alexou2** [comment] 2023-05-07 17:08
actually no. what I wanted to do was to have a regex that would do something like that `title.replaceAll(artistName, "");`.
is there documentation on how the code works?

**Comment by Moon-0xff** [comment] 2023-05-08 00:39
> what I wanted to do was to have a regex that would do something like that `title.replaceAll(artistName, "");`

From the regex field of that branch that's not possible, all it does is apply the provided regex to the title/artist/album string.

**What you want to do could be achieved by editing the `label.js` file.**  
`label.js` was designed with hacking in mind, it's a short file, well commented (i hope), and the extensions passes the entire `players` interface to it (defined in `players.js`).

> Is there documentation on how the code works?

No, but the harder to read parts are commented, variable names are descriptive, and as we developed most of the features as a duo the PRs are full of information about the inner workings of the extension.

I *hope* the prerequisites for editing `label.js` are just programming knowledge, and reading the `players.js` file, but admittedly that file is not very clear, and it's short on comments.

There's also the issue that web browser don't pass information to the extension that could help distinguish between a youtube source and a non-youtube source.

**Comment by Moon-0xff** [comment] 2023-05-08 00:54
My initial idea would be to add a test case like:  
*if players.selected.address matches chrome's: add "Remaster" to the end of the `LAST_FIELD` string*
to the `buildLabel` function.

Assuming `LAST_FIELD` is `title`, and the `remove-remaster-text` option is enabled.

**Comment by Batwam** [comment] 2023-05-08 01:07
Assuming the below format:
![image](https://user-images.githubusercontent.com/56710655/236653461-7bb80a08-8d27-4b74-8891-73b4a5032f92.png)if playing music from youtube exclusively, it would be possible to exclude anything before ` - ` using regex. That would the most basic solution but could be fit for purpose and not require touching any js code.

Based on the screenshot above, chrome/youtube appear to display the artist name
![image](https://user-images.githubusercontent.com/56710655/236653449-79f544f0-86b3-44dd-a26d-2c6e344b0d92.png)
a neater solution could be to filter out `artist` from `title` by editing label.js.

I think that this is too niche to implement in the main code but one thing worth considering would be to provide the ability to specify which sources the filters should apply to, similarly to the Ignore/Allist lists?

**Comment by Moon-0xff** [comment] 2023-05-08 01:29
> I think that this is too niche to implement in the main code but one thing worth considering would be to provide the ability to specify which sources the filters should apply to, similarly to the Ignore/Allist lists?

That referring to #31, which I'm thinking of discarding altogether.

It's not that #31 isn't useful or a good addition to the extension, but it requires extra effort in our side, and regex knowledge the user's side.  
And if the user knows how to write regex, isn't a stretch that could also edit the source code.

**Comment by Batwam** [comment] 2023-05-08 04:48
@Moon-0xff let's discuss in #31

**Comment by Batwam** [comment] 2023-05-17 14:35
Seems like this feature isn't going to be implemented as a little bit too niche but can be achieved using the `regex` filtering fork provided and/or editing the code. So, should we close this as `won't fix`?

**Comment by Moon-0xff** [comment] 2023-05-17 21:45
Not at all! The issue is **not** about adding this change, but **how** to do it.  
And we do indeed lack some sort of internal documentation and the code can be clearer and easier to edit in some places.

As a response I've added [HACKING.md](https://github.com/Moon-0xff/gnome-mpris-label/blob/main/HACKING.md) 2 days ago and I'm partially rewriting `label.js` so it's easier to edit.

(Do note that  `HACKING.md` surely needs more work)

**Comment by Moon-0xff** [comment] 2023-05-22 06:37
As mentioned, I added a guide to modify the extension (although still needs work) and rewritten the `label.js` to make changes like this easier to add.

I was thinking of leaving the PR open for a while as I was unsure if the code *layout* of the file was up to the task.

But I've added my [idea](https://github.com/Moon-0xff/gnome-mpris-label/issues/52#issuecomment-1537593817) in *a few seconds* so I think it's good enough.

Here's a diff for the changes, they are untested though
```diff
diff --git a/label.js b/label.js
index 6798f7b..4a5246b 100644
--- a/label.js
+++ b/label.js
@@ -46,6 +46,10 @@ var buildLabel = function buildLabel(players){
 	let labelstring = "";
 	fields.forEach(field => {
 		let fieldString = stringFromMetadata(field,metadata); //"extract" the string from metadata
+
+		if(players.selected.identity == "Chromium" && field == "xesam:title" && fieldString.includes("-"))
+			fieldString += "Remastered";
+
 		fieldString = parseMetadataField(fieldString); //check, filter, customize and add divider to the extracted string
 		labelstring += fieldString; //add it to the string to be displayed
 	});
```
`$ patch < [file with the diff]` while on the working directory to apply it.

**Comment by Moon-0xff** [comment] 2023-05-24 05:38
Closing this. The changes *should* aid to any newcomer to edit the extension (I hope). Some work is still needed to make `HACKING.md` a bit more useful, but overall it should be *enough* at least as a starting point.

Last comment *might* just answer the starting question (haven't tested it) but in any case I'm marking this as completed 😉

**Closed by Moon-0xff** 2023-05-24 05:38 UTC
